name: "vflow"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: go test -v ./... -timeout 1m
      - name: Build
        run: make build
